/* Generated by spimdisasm 1.13.2 */
.include "macro.inc"
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .text

glabel func_800E7F9C
/* 879C 800E7F9C 0800E003 */  jr         $ra
/* 87A0 800E7FA0 00000000 */   nop

glabel _start
/* 87A4 800E7FA4 14801C3C */  lui        $gp, (0x80140000 >> 16)
/* 87A8 800E7FA8 14ED9C27 */  addiu      $gp, $gp, -0x12EC
/* 87AC 800E7FAC 35960308 */  j          func_800E58D4
/* 87B0 800E7FB0 00000000 */   nop

glabel func_800E7FB4
/* 87B4 800E7FB4 A0000A24 */  addiu      $t2, $zero, 0xA0
/* 87B8 800E7FB8 08004001 */  jr         $t2
/* 87BC 800E7FBC 3F000924 */   addiu     $t1, $zero, 0x3F
