__addr  = 0x80018000;

/* put symbols here that the non-decomped assemblies need */
D_7FFFFF = 0x7FFFFF;
D_80000004 = 0x80000004;
kernelbuf = 0xA000DF00;
tmpfilebuf = 0x80100000;
TIMER_REGS = 0x1f801100;
KER_DATE = 0xbfc00100;
CONSOLE_TYPE = 0xbfc00104;
jmptable = 0x80010000;
jt = jmptable;
g_GameConfig = 80014000;
ww_second = ww_global_loc + 1;
ww_sector = ww_global_loc + 2;
tmpfilebuf = 0x80100000;