.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.13.2 */

glabel D_800E0000
.incbin "sprtdata.bin"

glabel D_800E0AEC
.incbin "sprttiles.bin"

glabel D_800EA96C
.incbin "clut0.bin"

glabel D_800EAB6C
.incbin "clut1.bin"

glabel D_800EAD6C
.incbin "clut2.bin"

# glabel D_800EAF74
glabel D_800EAF6C
.incbin "bunny.bin"

glabel jtbl_800EB874
/* C074 800EB874 7CBA0E80 */ .word .L800EBA7C
/* C078 800EB878 A4BA0E80 */ .word .L800EBAA4
/* C07C 800EB87C 54BC0E80 */ .word .L800EBC54
/* C080 800EB880 10BB0E80 */ .word .L800EBB10
/* C084 800EB884 7CBB0E80 */ .word .L800EBB7C
/* C088 800EB888 DCBB0E80 */ .word .L800EBBDC
/* C08C 800EB88C 28BC0E80 */ .word .L800EBC28
/* C090 800EB890 A4BC0E80 */ .word .L800EBCA4
