.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.13.2 */

glabel __main
/* BF3C 8002373C 0800E003 */  jr         $ra
/* BF40 80023740 00000000 */   nop

# Handwritten function
glabel _start
/* BF44 80023744 0480023C */  lui        $v0, %hi(D_80047E6C)
/* BF48 80023748 6C7E4224 */  addiu      $v0, $v0, %lo(D_80047E6C)
/* BF4C 8002374C 0580033C */  lui        $v1, %hi(D_80054924)
/* BF50 80023750 24496324 */  addiu      $v1, $v1, %lo(D_80054924)
.L80023754:
/* BF54 80023754 000040AC */  sw         $zero, 0x0($v0)
/* BF58 80023758 04004224 */  addiu      $v0, $v0, 0x4
/* BF5C 8002375C 2B084300 */  sltu       $at, $v0, $v1
/* BF60 80023760 FCFF2014 */  bnez       $at, .L80023754
/* BF64 80023764 00000000 */   nop
/* BF68 80023768 04000224 */  addiu      $v0, $zero, 0x4
/* BF6C 8002376C 00000000 */  nop
/* BF70 80023770 00000000 */  nop
/* BF74 80023774 00000000 */  nop
/* BF78 80023778 00000000 */  nop
/* BF7C 8002377C 0280043C */  lui        $a0, %hi(D_800237F0)
/* BF80 80023780 F0378424 */  addiu      $a0, $a0, %lo(D_800237F0)
/* BF84 80023784 21208200 */  addu       $a0, $a0, $v0
/* BF88 80023788 0000828C */  lw         $v0, 0x0($a0)
/* BF8C 8002378C 0080083C */  lui        $t0, %hi(D_80000004)
/* BF90 80023790 25E84800 */  or         $sp, $v0, $t0
/* BF94 80023794 0580043C */  lui        $a0, %hi(D_80054924)
/* BF98 80023798 24498424 */  addiu      $a0, $a0, %lo(D_80054924)
/* BF9C 8002379C C0200400 */  sll        $a0, $a0, 3
/* BFA0 800237A0 C2200400 */  srl        $a0, $a0, 3
/* BFA4 800237A4 0480033C */  lui        $v1, %hi(stacksize)
/* BFA8 800237A8 4074638C */  lw         $v1, %lo(stacksize)($v1)
/* BFAC 800237AC 00000000 */  nop
/* BFB0 800237B0 23284300 */  subu       $a1, $v0, $v1
/* BFB4 800237B4 2328A400 */  subu       $a1, $a1, $a0
/* BFB8 800237B8 25208800 */  or         $a0, $a0, $t0
/* BFBC 800237BC 0580013C */  lui        $at, %hi(D_80048044)
/* BFC0 800237C0 44803FAC */  sw         $ra, %lo(D_80048044)($at)
/* BFC4 800237C4 04801C3C */  lui        $gp, (0x80040000 >> 16)
/* BFC8 800237C8 447D9C27 */  addiu      $gp, $gp, 0x7D44
/* BFCC 800237CC 21F0A003 */  addu       $fp, $sp, $zero
/* BFD0 800237D0 EE8E000C */  jal        k_InitHeap
/* BFD4 800237D4 04008420 */   addi      $a0, $a0, %lo(D_80000004) # handwritten instruction
/* BFD8 800237D8 05801F3C */  lui        $ra, %hi(D_80048044)
/* BFDC 800237DC 4480FF8F */  lw         $ra, %lo(D_80048044)($ra)
/* BFE0 800237E0 00000000 */  nop
/* BFE4 800237E4 8167000C */  jal        main
/* BFE8 800237E8 00000000 */   nop
/* BFEC 800237EC 4D000000 */  break      0, 1
glabel D_800237F0
/* BFF0 800237F0 00002000 */  .word      0x00200000                    # sll        $zero, $zero, 0 # 00200000 <InstrIdType: CPU_SPECIAL>
/* BFF4 800237F4 00002000 */  .word      0x00200000                    # sll        $zero, $zero, 0 # 00200000 <InstrIdType: CPU_SPECIAL>
/* BFF8 800237F8 00002000 */  .word      0x00200000                    # sll        $zero, $zero, 0 # 00200000 <InstrIdType: CPU_SPECIAL>
/* BFFC 800237FC 00002000 */  .word      0x00200000                    # sll        $zero, $zero, 0 # 00200000 <InstrIdType: CPU_SPECIAL>
