.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.13.2 */

/* this is actually in the final file (initialized to 0) */

glabel vol_full
/* 30684 80047E9C */ .space 0x02

glabel D_80047E9E
/* 30686 80047E9E */ .space 0x01

glabel D_80047E9F
/* 30687 80047E9F */ .space 0x05

glabel D_80047ECC
/* 306B4 80047ECC */ .space 0x01

glabel D_80047ECD
/* 306B5 80047ECD */ .space 0x07

glabel bgm_counter
/* 3072C 80047F44 */ .space 0x08

glabel bgm_target
/* 30734 80047F4C */ .space 0x08

glabel bgm_finished
/* 3073C 80047F54 */ .space 0x08

glabel font_ptr8
/* 30744 80047F5C */ .space 0x08

glabel font_ptr16
/* 3074C 80047F64 */ .space 0x08

glabel D_80047FAC
/* 30794 80047FAC */ .space 0x08

/* MORE BSS BROUGHT OVER FROM THE SYMBOL FILE */

glabel D_80048004
    .space 0x8

glabel D_8004800C
    .space 0x8

glabel D_8004D0E0
    .space 0x18

glabel D_8004DCF8
    .space 0x88

glabel D_800521F8
    .space 0x20

glabel D_80052220
    .space 0x4

glabel D_80052224
    .space 0x4

glabel D_80052228
    .space 0x2

glabel D_8005222A
    .space 0x2

glabel D_8005222C
    .space 0x2

glabel D_8005222E
    .space 0xa

glabel D_80052238
    .space 0x6

glabel D_8005223E
    .space 0x2

glabel D_80052240
    .space 0x2

glabel D_80052242
    .space 0x2

glabel D_80052244
    .space 0x4

glabel D_80052248
    .space 0x4

glabel D_8005224C
    .space 0x4

glabel D_80052250
    .space 0x4

glabel D_80052254
    .space 0x4

glabel D_80052258
    .space 0x4

glabel D_8005225C
    .space 0x4

glabel D_80052260
    .space 0x4

glabel D_80052264
    .space 0x4

glabel D_80052268
    .space 0x4

glabel D_8005226C
    .space 0x4

glabel D_80052270
    .space 0x4

glabel D_80052274
    .space 0x14

glabel D_80052288
    .space 0x5c

glabel D_800522E4
    .space 0x4

glabel D_800522E8
    .space 0x4

glabel D_800522EC
    .space 0x4

glabel D_800522F0
    .space 0x4

glabel D_800522F4
    .space 0x4

glabel D_800522F8
    .space 0x84

glabel D_8005237C
    .space 0x4

glabel D_80052380
    .space 0x4

glabel D_80054754
    .space 0x4

glabel D_80054758
    .space 0x4

glabel D_8005475C
    .space 0x1

glabel D_8005475D
    .space 0x1

glabel D_8005475E
    .space 0x18e

glabel D_800548EC
    .space 0x8

glabel D_800548F4
    .space 0x4

glabel D_800548F8
    .space 0x4

glabel D_800548FC
    .space 0x8

glabel D_80054904
    .space 0x4

glabel D_80054908
    .space 0x2

glabel D_8005490A
    .space 0x2

glabel D_8005490C
    .space 0x4

glabel D_80054910
    .space 0x4

glabel D_80054914
    .space 0x8

glabel D_8005491C
    .space 0x4

glabel D_80054920
    .space 0x4

/* this is supposed to be the bottom of heap */
glabel D_80054924
    .space 0x4
