.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.13.2 */

glabel D_80047E84
/* 3066C 80047E84 */ .space 0x08

glabel D_80047E8C
/* 30674 80047E8C */ .space 0x08

glabel vol_full
/* 30684 80047E9C */ .space 0x02

glabel D_80047E9E
/* 30686 80047E9E */ .space 0x01

glabel D_80047E9F
/* 30687 80047E9F */ .space 0x05

glabel D_80047EA4
/* 3068C 80047EA4 */ .space 0x08

glabel D_80047EAC
/* 30694 80047EAC */ .space 0x08

glabel D_80047EC4
/* 306AC 80047EC4 */ .space 0x08

glabel D_80047ECC
/* 306B4 80047ECC */ .space 0x01

glabel D_80047ECD
/* 306B5 80047ECD */ .space 0x07

glabel D_80047EE4
/* 306CC 80047EE4 */ .space 0x08

glabel D_80047EEC
/* 306D4 80047EEC */ .space 0x08

glabel D_80047F24
/* 3070C 80047F24 */ .space 0x08

glabel D_80047F44
/* 3072C 80047F44 */ .space 0x08

glabel D_80047F4C
/* 30734 80047F4C */ .space 0x08

glabel D_80047F54
/* 3073C 80047F54 */ .space 0x08

glabel font_ptr8
/* 30744 80047F5C */ .space 0x08

glabel font_ptr16
/* 3074C 80047F64 */ .space 0x08

glabel D_80047F6C
/* 30754 80047F6C */ .space 0x08

glabel D_80047F74
/* 3075C 80047F74 */ .space 0x08

glabel D_80047F7C
/* 30764 80047F7C */ .space 0x08

glabel D_80047F84
/* 3076C 80047F84 */ .space 0x08

glabel D_80047F8C
/* 30774 80047F8C */ .space 0x08

glabel D_80047F94
/* 3077C 80047F94 */ .space 0x07

glabel D_80047F9B
/* 30783 80047F9B */ .space 0x01

glabel D_80047F9C
/* 30784 80047F9C */ .space 0x08

glabel D_80047FA4
/* 3078C 80047FA4 */ .space 0x08

glabel D_80047FAC
/* 30794 80047FAC */ .space 0x08

glabel D_80047FB4
/* 3079C 80047FB4 */ .space 0x08

glabel D_80047FBC
/* 307A4 80047FBC */ .space 0x08

glabel D_80047FC4
/* 307AC 80047FC4 */ .space 0x08

glabel D_80047FCC
/* 307B4 80047FCC */ .space 0x08

glabel D_80047FD4
/* 307BC 80047FD4 */ .space 0x08

glabel D_80047FDC
/* 307C4 80047FDC */ .space 0x08

glabel D_80047FE4
/* 307CC 80047FE4 */ .space 0x08

glabel D_80047FEC
/* 307D4 80047FEC */ .space 0x08

glabel D_80047FF4
/* 307DC 80047FF4 */ .space 0x08

glabel D_80047FFC
/* 307E4 80047FFC */ .space 0x04
