.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.13.2 */

glabel D_80018788
/* F88 80018788 */ .asciz "intr timeout(%04x:%04x)\n"
                      .balign 4

glabel D_800187A4
/* FA4 800187A4 */ .asciz "DMA bus error: code=%08x\n"
                      .balign 4

glabel D_800187C0
/* FC0 800187C0 */ .asciz "VSync: timeout\n"
                      .balign 4
