.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.13.2 */

glabel D_80018240
/* A40 80018240 */ .asciz "ResetGraph(%d)...\n"
                      .balign 4

glabel D_80018254
/* A54 80018254 */ .asciz "SetGraphReverse(%d)...\n"
                      .balign 4

glabel D_8001826C
/* A6C 8001826C */ .asciz "SetGraphDebug:level:%d,type:%d reverse:%d\n"
                      .balign 4

glabel D_80018298
/* A98 80018298 */ .asciz "SetGraphQueue(%d)...\n"
                      .balign 4

glabel D_800182B0
/* AB0 800182B0 */ .asciz "DrawSyncCallback(%08x)...\n"
                      .balign 4

glabel D_800182CC
/* ACC 800182CC */ .asciz "SetDispMask(%d)...\n"
                      .balign 4

glabel D_800182E0
/* AE0 800182E0 */ .asciz "DrawSync(%d)...\n"
                      .balign 4

glabel D_800182F4
/* AF4 800182F4 */ .asciz "%s:bad RECT"
                      .balign 4

glabel D_80018300
/* B00 80018300 */ .asciz "(%d,%d)-(%d,%d)\n"
                      .balign 4

glabel D_80018314
/* B14 80018314 */ .asciz "%s:"
                      .balign 4

glabel D_80018318
/* B18 80018318 */ .asciz "ClearImage"
                      .balign 4

glabel D_80018324
/* B24 80018324 */ .asciz "LoadImage"
                      .balign 4

glabel D_80018330
/* B30 80018330 */ .asciz "StoreImage"
                      .balign 4

glabel D_8001833C
/* B3C 8001833C */ .asciz "MoveImage"
                      .balign 4

glabel D_80018348
/* B48 80018348 */ .asciz "ClearOTag(%08x,%d)...\n"
                      .balign 4

glabel D_80018360
/* B60 80018360 */ .asciz "ClearOTagR(%08x,%d)...\n"
                      .balign 4

glabel D_80018378
/* B78 80018378 */ .asciz "DrawOTag(%08x)...\n"
                      .balign 4

glabel D_8001838C
/* B8C 8001838C */ .asciz "PutDrawEnv(%08x)...\n"
                      .balign 4

glabel D_800183A4
/* BA4 800183A4 */ .asciz "PutDispEnv(%08x)...\n"
                      .balign 4

glabel D_800183BC
/* BBC 800183BC */ .asciz "GPU_exeque: null func.\n"
                      .balign 4

glabel D_800183D4
/* BD4 800183D4 */ .asciz "GPU timeout:que=%d,stat=%08x,chcr=%08x,madr=%08x\n"
                      .balign 4

glabel D_80018408
/* C08 80018408 74706167 */ .word 0x67617074
/* C0C 8001840C 653A2028 */ .word 0x28203A65
/* C10 80018410 25642C25 */ .word 0x252C6425
/* C14 80018414 642C2564 */ .word 0x64252C64
/* C18 80018418 2C256429 */ .word 0x2964252C
/* C1C 8001841C 0A000000 */ .word 0x0000000A

glabel D_80018420
/* C20 80018420 */ .asciz "clut: (%d,%d)\n"
                      .balign 4

glabel D_80018430
/* C30 80018430 */ .asciz "clip (%3d,%3d)-(%d,%d)\n"
                      .balign 4

glabel D_80018448
/* C48 80018448 */ .asciz "ofs  (%3d,%3d)\n"
                      .balign 4

glabel D_80018458
/* C58 80018458 */ .asciz "tw   (%d,%d)-(%d,%d)\n"
                      .balign 4

glabel D_80018470
/* C70 80018470 */ .asciz "dtd   %d\n"
                      .balign 4

glabel D_8001847C
/* C7C 8001847C */ .asciz "dfe   %d\n"
                      .balign 4

glabel D_80018488
/* C88 80018488 */ .asciz "disp   (%3d,%3d)-(%d,%d)\n"
                      .balign 4

glabel D_800184A4
/* CA4 800184A4 */ .asciz "screen (%3d,%3d)-(%d,%d)\n"
                      .balign 4

glabel D_800184C0
/* CC0 800184C0 */ .asciz "isinter %d\n"
                      .balign 4

glabel D_800184CC
/* CCC 800184CC */ .asciz "isrgb24 %d\n"
                      .balign 4
