.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.13.2 */

glabel D_80018144
/* 944 80018144 */ .asciz "MDEC_rest:bad option(%d)\n"
                      .balign 4

glabel D_80018160
/* 960 80018160 */ .asciz "MDEC_in_sync"
                      .balign 4

glabel D_80018170
/* 970 80018170 */ .asciz "MDEC_out_sync"
                      .balign 4

glabel D_80018180
/* 980 80018180 */ .asciz "\t DMA=(%d,%d), ADDR=(0x%08x->0x%08x)\n"
                      .balign 4

glabel D_800181A8
/* 9A8 800181A8 */ .asciz "\t FIFO=(%d,%d),BUSY=%d,DREQ=(%d,%d),RGB24=%d,STP=%d\n"
                      .balign 4

glabel D_800181E0
/* 9E0 800181E0 */ .asciz "%s timeout:\n"
                      .balign 4

glabel D_800181F0
/* 9F0 800181F0 */ .asciz "MDEC_vlec: invalid VLC ID\n"
                      .balign 4
/* A0C 8001820C */ .asciz "$Id: sys.c,v 1.83 1995/05/25 13:43:27 suzu Exp $"
                      .balign 4
