/* Generated by spimdisasm 1.13.2 */

glabel k_ChangeClearPAD
/* C3A8 80023BA8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C3AC 80023BAC 08004001 */  jr         $t2
/* C3B0 80023BB0 5B000924 */   addiu     $t1, $zero, 0x5B
/* C3B4 80023BB4 00000000 */  nop

glabel k_InitHeap
/* C3B8 80023BB8 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C3BC 80023BBC 08004001 */  jr         $t2
/* C3C0 80023BC0 39000924 */   addiu     $t1, $zero, 0x39
/* C3C4 80023BC4 00000000 */  nop

glabel k_nextfile
/* C3C8 80023BC8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C3CC 80023BCC 08004001 */  jr         $t2
/* C3D0 80023BD0 43000924 */   addiu     $t1, $zero, 0x43
/* C3D4 80023BD4 00000000 */  nop

glabel k_Exec
/* C3D8 80023BD8 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C3DC 80023BDC 08004001 */  jr         $t2
/* C3E0 80023BE0 43000924 */   addiu     $t1, $zero, 0x43
/* C3E4 80023BE4 00000000 */  nop

glabel k_OpenEvent
/* C3E8 80023BE8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C3EC 80023BEC 08004001 */  jr         $t2
/* C3F0 80023BF0 08000924 */   addiu     $t1, $zero, 0x8
/* C3F4 80023BF4 00000000 */  nop

glabel k_read
/* C3F8 80023BF8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C3FC 80023BFC 08004001 */  jr         $t2
/* C400 80023C00 34000924 */   addiu     $t1, $zero, 0x34
/* C404 80023C04 00000000 */  nop

glabel k_TestEvent
/* C408 80023C08 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C40C 80023C0C 08004001 */  jr         $t2
/* C410 80023C10 0B000924 */   addiu     $t1, $zero, 0xB
/* C414 80023C14 00000000 */  nop

glabel k_ExitCriticalSection
/* C418 80023C18 02000424 */  addiu      $a0, $zero, 0x2
/* C41C 80023C1C 0C000000 */  syscall    0
/* C420 80023C20 0800E003 */  jr         $ra
/* C424 80023C24 00000000 */   nop

glabel k_open
/* C428 80023C28 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C42C 80023C2C 08004001 */  jr         $t2
/* C430 80023C30 32000924 */   addiu     $t1, $zero, 0x32
/* C434 80023C34 00000000 */  nop

glabel k_firstfile2
/* C438 80023C38 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C43C 80023C3C 08004001 */  jr         $t2
/* C440 80023C40 42000924 */   addiu     $t1, $zero, 0x42
/* C444 80023C44 00000000 */  nop

glabel k_FlushCache
/* C448 80023C48 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C44C 80023C4C 08004001 */  jr         $t2
/* C450 80023C50 44000924 */   addiu     $t1, $zero, 0x44
/* C454 80023C54 00000000 */  nop

glabel k_malloc
/* C458 80023C58 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C45C 80023C5C 08004001 */  jr         $t2
/* C460 80023C60 33000924 */   addiu     $t1, $zero, 0x33
/* C464 80023C64 00000000 */  nop

glabel k_strcat
/* C468 80023C68 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C46C 80023C6C 08004001 */  jr         $t2
/* C470 80023C70 15000924 */   addiu     $t1, $zero, 0x15
/* C474 80023C74 00000000 */  nop

glabel k_printf
/* C478 80023C78 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C47C 80023C7C 08004001 */  jr         $t2
/* C480 80023C80 3F000924 */   addiu     $t1, $zero, 0x3F
/* C484 80023C84 00000000 */  nop

glabel k_strcpy
/* C488 80023C88 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C48C 80023C8C 08004001 */  jr         $t2
/* C490 80023C90 19000924 */   addiu     $t1, $zero, 0x19
/* C494 80023C94 00000000 */  nop

glabel k_card_load
/* C498 80023C98 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C49C 80023C9C 08004001 */  jr         $t2
/* C4A0 80023CA0 AC000924 */   addiu     $t1, $zero, 0xAC
/* C4A4 80023CA4 00000000 */  nop

glabel k_card_info
/* C4A8 80023CA8 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C4AC 80023CAC 08004001 */  jr         $t2
/* C4B0 80023CB0 AB000924 */   addiu     $t1, $zero, 0xAB
/* C4B4 80023CB4 00000000 */  nop

glabel k_card_auto
/* C4B8 80023CB8 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C4BC 80023CBC 08004001 */  jr         $t2
/* C4C0 80023CC0 AD000924 */   addiu     $t1, $zero, 0xAD
/* C4C4 80023CC4 00000000 */  nop

glabel k_card_write
/* C4C8 80023CC8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C4CC 80023CCC 08004001 */  jr         $t2
/* C4D0 80023CD0 4E000924 */   addiu     $t1, $zero, 0x4E
/* C4D4 80023CD4 00000000 */  nop

glabel k_InitCARD2
/* C4D8 80023CD8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C4DC 80023CDC 08004001 */  jr         $t2
/* C4E0 80023CE0 4A000924 */   addiu     $t1, $zero, 0x4A
/* C4E4 80023CE4 00000000 */  nop

glabel k_StopCARD2
/* C4E8 80023CE8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C4EC 80023CEC 08004001 */  jr         $t2
/* C4F0 80023CF0 4C000924 */   addiu     $t1, $zero, 0x4C
/* C4F4 80023CF4 00000000 */  nop

glabel k_StartCARD2
/* C4F8 80023CF8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C4FC 80023CFC 08004001 */  jr         $t2
/* C500 80023D00 4B000924 */   addiu     $t1, $zero, 0x4B
/* C504 80023D04 00000000 */  nop

glabel k_bu_init
/* C508 80023D08 A0000A24 */  addiu      $t2, $zero, 0xA0
/* C50C 80023D0C 08004001 */  jr         $t2
/* C510 80023D10 70000924 */   addiu     $t1, $zero, 0x70
/* C514 80023D14 00000000 */  nop

glabel k_new_card
/* C518 80023D18 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C51C 80023D1C 08004001 */  jr         $t2
/* C520 80023D20 50000924 */   addiu     $t1, $zero, 0x50
/* C524 80023D24 00000000 */  nop

glabel k_card_read
/* C528 80023D28 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C52C 80023D2C 08004001 */  jr         $t2
/* C530 80023D30 4F000924 */   addiu     $t1, $zero, 0x4F
/* C534 80023D34 00000000 */  nop
