/* Generated by spimdisasm 1.13.2 */

glabel func_800239A0
/* C1A0 800239A0 0800E003 */  jr         $ra
/* C1A4 800239A4 00000000 */   nop

glabel k_CloseEvent
/* C1A8 800239A8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C1AC 800239AC 08004001 */  jr         $t2
/* C1B0 800239B0 09000924 */   addiu     $t1, $zero, 0x9
/* C1B4 800239B4 00000000 */  nop

glabel k_Krom2RawAdd
/* C1B8 800239B8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C1BC 800239BC 08004001 */  jr         $t2
/* C1C0 800239C0 51000924 */   addiu     $t1, $zero, 0x51
/* C1C4 800239C4 00000000 */  nop

glabel k_EnterCriticalSection
/* C1C8 800239C8 01000424 */  addiu      $a0, $zero, 0x1
/* C1CC 800239CC 0C000000 */  syscall    0
/* C1D0 800239D0 0800E003 */  jr         $ra
/* C1D4 800239D4 00000000 */   nop

glabel k_lseek
/* C1D8 800239D8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C1DC 800239DC 08004001 */  jr         $t2
/* C1E0 800239E0 33000924 */   addiu     $t1, $zero, 0x33
/* C1E4 800239E4 00000000 */  nop

glabel k_close
/* C1E8 800239E8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C1EC 800239EC 08004001 */  jr         $t2
/* C1F0 800239F0 36000924 */   addiu     $t1, $zero, 0x36
/* C1F4 800239F4 00000000 */  nop

glabel k_write
/* C1F8 800239F8 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C1FC 800239FC 08004001 */  jr         $t2
/* C200 80023A00 35000924 */   addiu     $t1, $zero, 0x35
/* C204 80023A04 00000000 */  nop

glabel k_EnableEvent
/* C208 80023A08 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C20C 80023A0C 08004001 */  jr         $t2
/* C210 80023A10 0C000924 */   addiu     $t1, $zero, 0xC
/* C214 80023A14 00000000 */  nop

glabel k_erase
/* C218 80023A18 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C21C 80023A1C 08004001 */  jr         $t2
/* C220 80023A20 45000924 */   addiu     $t1, $zero, 0x45
/* C224 80023A24 00000000 */  nop

glabel k_format
/* C228 80023A28 B0000A24 */  addiu      $t2, $zero, 0xB0
/* C22C 80023A2C 08004001 */  jr         $t2
/* C230 80023A30 41000924 */   addiu     $t1, $zero, 0x41
/* C234 80023A34 00000000 */  nop
