.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.13.2 */

glabel D_800E0000
/* 800 800E0000 */ .asciz "$$$$$$$$.$$$"
                      .balign 4
/* 810 800E0010 */ .asciz "MOVIE\\W6ST2.STR"
                      .balign 4
/* 820 800E0020 */ .asciz "MOVIE\\W6ST1.STR"
                      .balign 4
/* 830 800E0030 */ .asciz "MOVIE\\W5ST.STR"
                      .balign 4
/* 840 800E0040 */ .asciz "MOVIE\\W4ST.STR"
                      .balign 4
/* 850 800E0050 */ .asciz "MOVIE\\W3ST.STR"
                      .balign 4
/* 860 800E0060 */ .asciz "MOVIE\\W2ST.STR"
                      .balign 4
/* 870 800E0070 */ .asciz "MOVIE\\W1ST.STR"
                      .balign 4

glabel D_800E0080
/* 880 800E0080 */ .asciz "PUSH START BUTTON"
                      .balign 4
/* 894 800E0094 */ .asciz ""
                      .balign 4

glabel D_800E00AC
/* 8AC 800E00AC */ .asciz "MOVIE\\NL_END1.STR"
                      .balign 4

glabel D_800E00C0
/* 8C0 800E00C0 */ .asciz "MOVIE\\NL_END2.STR"
                      .balign 4

glabel D_800E00D4
/* 8D4 800E00D4 */ .asciz "MOVIE\\EX_END1.STR"
                      .balign 4

glabel D_800E00E8
/* 8E8 800E00E8 */ .asciz "MOVIE\\EX_END2.STR"
                      .balign 4


.align 2
glabel jtbl_800E0230
/* A30 800E0230 40A30E80 */ .word .L800EA340
/* A34 800E0234 40A30E80 */ .word .L800EA340
/* A38 800E0238 40A30E80 */ .word .L800EA340
/* A3C 800E023C 2CA30E80 */ .word .L800EA32C
/* A40 800E0240 2CA30E80 */ .word .L800EA32C
/* A44 800E0244 2CA30E80 */ .word .L800EA32C
/* A48 800E0248 0CA30E80 */ .word .L800EA30C
/* A4C 800E024C 0CA30E80 */ .word .L800EA30C
/* A50 800E0250 0CA30E80 */ .word .L800EA30C
