.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.13.2 */

glabel D_800E0000
/* 800 800E0000 */ .asciz "$$$$$$$$.$$$"
                      .balign 4
/* 810 800E0010 */ .asciz "MOVIE\\W6ST2.STR"
                      .balign 4
/* 820 800E0020 */ .asciz "MOVIE\\W6ST1.STR"
                      .balign 4
/* 830 800E0030 */ .asciz "MOVIE\\W5ST.STR"
                      .balign 4
/* 840 800E0040 */ .asciz "MOVIE\\W4ST.STR"
                      .balign 4
/* 850 800E0050 */ .asciz "MOVIE\\W3ST.STR"
                      .balign 4
/* 860 800E0060 */ .asciz "MOVIE\\W2ST.STR"
                      .balign 4
/* 870 800E0070 */ .asciz "MOVIE\\W1ST.STR"
                      .balign 4

glabel D_800E0080
/* 880 800E0080 */ .asciz "PUSH START BUTTON"
                      .balign 4
/* 894 800E0094 */ .asciz ""
                      .balign 4

.align 3
glabel jtbl_800E0098
/* 898 800E0098 D4410E80 */ .word .L800E41D4
/* 89C 800E009C F0410E80 */ .word .L800E41F0
/* 8A0 800E00A0 40420E80 */ .word .L800E4240
/* 8A4 800E00A4 80420E80 */ .word .L800E4280
/* 8A8 800E00A8 A8420E80 */ .word .L800E42A8

glabel D_800E00AC
/* 8AC 800E00AC */ .asciz "MOVIE\\NL_END1.STR"
                      .balign 4

glabel D_800E00C0
/* 8C0 800E00C0 */ .asciz "MOVIE\\NL_END2.STR"
                      .balign 4

glabel D_800E00D4
/* 8D4 800E00D4 */ .asciz "MOVIE\\EX_END1.STR"
                      .balign 4

glabel D_800E00E8
/* 8E8 800E00E8 */ .asciz "MOVIE\\EX_END2.STR"
                      .balign 4
/* 8FC 800E00FC */ .asciz "VAB\\W6_3.VAB"
                      .balign 4
/* 90C 800E010C */ .asciz "VAB\\W6_2.VAB"
                      .balign 4
/* 91C 800E011C */ .asciz "VAB\\W6_1.VAB"
                      .balign 4
/* 92C 800E012C */ .asciz "VAB\\W5_3.VAB"
                      .balign 4
/* 93C 800E013C */ .asciz "VAB\\W5_2.VAB"
                      .balign 4
/* 94C 800E014C */ .asciz "VAB\\W5_1.VAB"
                      .balign 4
/* 95C 800E015C */ .asciz "VAB\\W4_3.VAB"
                      .balign 4
/* 96C 800E016C */ .asciz "VAB\\W4_2.VAB"
                      .balign 4
/* 97C 800E017C */ .asciz "VAB\\W4_1.VAB"
                      .balign 4
/* 98C 800E018C */ .asciz "VAB\\W3_3.VAB"
                      .balign 4
/* 99C 800E019C */ .asciz "VAB\\W3_2.VAB"
                      .balign 4
/* 9AC 800E01AC */ .asciz "VAB\\W3_1.VAB"
                      .balign 4
/* 9BC 800E01BC */ .asciz "VAB\\W2_3.VAB"
                      .balign 4
/* 9CC 800E01CC */ .asciz "VAB\\W2_2.VAB"
                      .balign 4
/* 9DC 800E01DC */ .asciz "VAB\\W2_1.VAB"
                      .balign 4
/* 9EC 800E01EC */ .asciz "VAB\\W1_3.VAB"
                      .balign 4
/* 9FC 800E01FC */ .asciz "VAB\\W1_2.VAB"
                      .balign 4
/* A0C 800E020C */ .asciz "VAB\\W1_1.VAB"
                      .balign 4

glabel D_800E021C
/* A1C 800E021C */ .asciz "VAB file Reload\n"
                      .balign 4
.align 2
glabel jtbl_800E0230
/* A30 800E0230 40A30E80 */ .word .L800EA340
/* A34 800E0234 40A30E80 */ .word .L800EA340
/* A38 800E0238 40A30E80 */ .word .L800EA340
/* A3C 800E023C 2CA30E80 */ .word .L800EA32C
/* A40 800E0240 2CA30E80 */ .word .L800EA32C
/* A44 800E0244 2CA30E80 */ .word .L800EA32C
/* A48 800E0248 0CA30E80 */ .word .L800EA30C
/* A4C 800E024C 0CA30E80 */ .word .L800EA30C
/* A50 800E0250 0CA30E80 */ .word .L800EA30C
